apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: dinesykmeldte
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://www-gcp.dev.nav.no/arbeidsgiver/sykmeldte'
  prometheus:
    enabled: true
    path: /arbeidsgiver/sykmeldte/api/internal/prometheus
  idporten:
    enabled: true
    sidecar:
      enabled: true
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: dinesykmeldte-backend
  liveness:
    path: /arbeidsgiver/sykmeldte/api/internal/is_alive
  readiness:
    path: /arbeidsgiver/sykmeldte/api/internal/is_ready
  env:
    - name: NEXT_PUBLIC_BASE_PATH
      value: /arbeidsgiver/sykmeldte
    - name: RUNTIME_ENVIRONMENT
      value: dev
    - name: RUNTIME_VERSION
      value: {{version}}
    - name: DINE_SYKMELDTE_BACKEND_SCOPE
      value: dev-gcp:teamsykmelding:dinesykmeldte-backend
    - name: DINE_SYKMELDTE_BACKEND_URL
      value: http://dinesykmeldte-backend
    - name: ASSET_PREFIX
      value: 'https://cdn.nav.no/teamsykmelding/dinesykmeldte'
    - name: AMPLITUDE_ENABLED
      value: 'true'
