name: Build and push
on: push
env:
  branchname: ${{ github.ref_name }}
  docker_image: ghcr.io/navikt/dinesykmeldte:${{ github.sha }}
  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
jobs:
  snyk-monitor:
    if: github.ref == 'refs/heads/main'
    name: monitor dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --org=teamsykmelding --severity-threshold=high
  snyk-test:
    name: analyze dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --org=teamsykmelding --severity-threshold=high
  build:
    name: build and push docker image
    runs-on: ubuntu-latest
    permissions:
      packages: 'write'
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install yarn dependencies
        run: yarn --immutable
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build app
        run: yarn build
        env:
          ENABLE_SENTRY: true
          SENTRY_URL: https://sentry.gc.nav.no/
          SENTRY_ORG: nav
          SENTRY_PROJECT: dinesykmeldte
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - name: Upload static files to NAV CDN dev
        uses: nais/frontend-plattform-cdn-upload-action@main
        with:
          cdn-environment: cdn.dev.nav.no
          cdn-team-name: teamsykmelding
          source: ./.next/static
          destination: '/dinesykmeldte/_next'
      - name: Upload static files to NAV CDN prod
        if: github.ref == 'refs/heads/main'
        uses: nais/frontend-plattform-cdn-upload-action@main
        with:
          cdn-environment: cdn.nav.no
          cdn-team-name: teamsykmelding
          source: ./.next/static
          destination: '/dinesykmeldte/_next'
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.docker_image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            "NPM_AUTH_TOKEN=${{ secrets.READER_TOKEN }}"

  deploy-to-dev-gcp:
    name: deploy to nais dev
    needs: [snyk-test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais-dev-gcp.yaml
          VAR: image=${{ env.docker_image }},version=${{ github.sha }}

  deploy-to-labs-gcp:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/labs')
    name: deploy to nais demo
    needs: [snyk-test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: labs-gcp
          RESOURCE: nais-labs-gcp.yaml
          VAR: image=${{ env.docker_image }}

  deploy:
    if: github.ref == 'refs/heads/main'
    name: deploy to nais
    needs: [snyk-test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais-prod-gcp.yaml
          VAR: image=${{ env.docker_image }},version=${{ github.sha }}
